# Site settings
title: Home | Tsien's Blog
email: fcqian@nuaa.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  A place where I try to find myself.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://github.com" # the base hostname & protocol for your site
github_username:  Tsien

# Build settings
markdown: kramdown
