# Site settings
title: Home | Tsien's Blog
email: fcqian@nuaa.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  A place where I try to find myself.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tsien.github.io" # the base hostname & protocol for your site
github_username:  Tsien

# Build settings
markdown: kramdown
source: /Users/Tsien/Documents/Projects/tsien.github.com

# This tells the paginator to break pages at ten posts. 
paginate: 2
